#!/usr/bin/python

# OIDs used:
# Webio-Digital-MIB::wtWebioEA2x2-24VInputCounterClear.1                     .1.3.6.1.4.1.5040.1.2.30.1.3.1.3.1
#
# Scan function looks for Enterprise 'Webio-Digital-MIB' OID and if it exists we continue

# Author: Rolf Koch - rolf.koch@netcetera.com - http://netcetera.com

def inventory_webiomotion(info):
    yield 'Motion', None

def check_webiomotion(item, _no_params, info):
    for index, value  in enumerate(info[0]):
        motionraw=value
        motion = int(motionraw[0])
        motion_rate_avg = 0
        motion_current = 0
        timestamp = None
        if 'Motion'  in item:
                timestamp = time.time()
                try:
                        motion_rate_avg = get_average("motion" , timestamp, motion, 120 / 60.0, True)
                        motion_current = round(motion - motion_rate_avg,1)
                except MKCounterWrapped:
                        yield (3, "exception" )

                #Check if we have Motion.. Motion is if average is more than 1 away from current motion counter or if it is negative

                if abs(motion_current) > 1.0:
                        yield (2, "Motion found 11" , [("motion", motion), ("motion_rate_avg", motion_rate_avg), ("motion_current", motion_current),])
                else:
                        yield (0, "No Motion 22", [("motion", motion), ("motion_rate_avg", motion_rate_avg), ("motion_current", motion_current),])




check_info["webiomotion"] = {
    "check_function"        : check_webiomotion,
    "inventory_function"    : inventory_webiomotion,
    "service_description"   : "%s",
    "has_perfdata"          : True,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0").startswith(".1.3.6.1.4.1.5040.1.2.30") and oid(".1.3.6.1.4.1.5040.1.2.30") is not None ,
    "snmp_info"             : [( ".1.3.6.1.4.1.5040.1.2.30", [
                                  "1.3.1.3.1",   # wtWebioEA2x2-24VInputCounterClear.1
                              ])],
}
